---
title: "HW"
author: "Zero"
date: "3/13/2019"
output: word_document
---
First we take a glance at the data set, we can find that the variables($x_1...x_9$) are in similar scale, so there is no need to normalize the data.
```{R}
require(lavaan)
summary(HolzingerSwineford1939)
```
Then, we introduce three latent factors, which are *visual, textual, speed*, in detail, *visual* contains variables $x_1,x_2,x_3$ in the dataset, *textual* contains variables $x_4,x_5,x_6$ in the dataset and *speed* contains variables $x_7,x_8,x_9$ in the dataset. *visual* is correlated with *textual* and *speed*, and *textual* is correlated with *speed*. We use the following code to construct the fators.
```{R}
visual =~ x1 + x2 + x3 
textual =~ x4 + x5 + x6 
speed =~ x7 + x8 + x9
HS.model <- ' visual =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed =~ x7 + x8 + x9 '
```
Finally, we use **cfa** function to achieve the confirmatory factor analysis, the summariesd results with all fit statistics are shown below.
```{R}
fit <- cfa(HS.model, data=HolzingerSwineford1939)
summary(fit, fit.measures=TRUE)
```
From the result, we can conclude that the fit statistics indicate unacceptable model fit. Reasons are as follows:

1.Chi-square is large. This shows that the model does not produce a small difference between observed and expected matrices.

2.Chi-square probability (< 0.0001) is unacceptable. Criteria for acceptable model is pr > 0.05.

3.Unexplained variance, residual, is un acceptable. Model RMSEA (0.092) is greater than the 0.06 or less criteria.

4.While CFI ((0.931) is larger than the acceptable criteria, 0.90, TFI (0.896) does not meet the threshold.

In summary, The factor structure of this model is not confirmed. No further investigation of the confirmatory model is necessary, we may proceed with exploratory factor analysis to determine the factor structure. 